issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable-all: true
  disable:
    - depguard # Unnecessary
    - execinquery # Archived
    - exhaustruct # too agressive - authors intended its use only for special cases
    - gomnd # Replaced by mnd
    - nlreturn # too aggressive, style
    - rowserrcheck # disabled - https://github.com/golangci/golangci-lint/issues/2649
    - sqlclosecheck # disabled - https://github.com/golangci/golangci-lint/issues/2649
    - wastedassign # disabled - https://github.com/golangci/golangci-lint/issues/2649
    - wsl # too aggressive, style
    - varnamelen # too aggressive, style
