version: 2.1
executors:
  go-build-essential:
    docker:
      - image: golang:1.22.5
jobs:
  lint:
    executor: go-build-essential
    steps:
      - checkout
      - run:
          name: lint
          command: make lint
  test:
    executor: go-build-essential
    steps:
      - checkout
      - run:
          name: test
          command: make test && bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  workflow:
    jobs:
      - lint
      - test
