name: Test

on:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-24.04-arm
    container:
      image: mere/ci:v0.15.0
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Git checkout
        run: |
          set -eu
          git init "$GITHUB_WORKSPACE"
          cd "$GITHUB_WORKSPACE"
          git remote add origin "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git"
          git -c http.extraHeader="Authorization: Bearer $GH_TOKEN" \
            fetch --depth=1 origin "$GITHUB_SHA"
          git checkout --detach FETCH_HEAD
      - name: Test
        run: |
          cd "$GITHUB_WORKSPACE"
          zig build test --summary all
